FROM tomcat:9.0-jdk17

# Remove default ROOT app
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy your WAR file into Tomcat webapps
COPY dist/car-workshop.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
